### ISSUE TITLE
Add integration with Travis CI

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-BlackSou#8]
Please configure integration with Travis CI:
* [x] Visit the [repo page in Travis CI](https://travis-ci.com/kpi-web-guild/django-girls-blog-BlackSou) and save it to your bookmarks.
* [x] Add TravisCI badge (master branch) to `README.md` with a single commit. (click [![Build Status](https://travis-ci.com/kpi-web-guild/django-girls-blog-BlackSou.svg?branch=master)](https://travis-ci.com/kpi-web-guild/django-girls-blog-BlackSou) next to octocat icon on [this page](https://travis-ci.com/kpi-web-guild/django-girls-blog-BlackSou)).
* [x] Create a new branch called `feature/8-travis-ci-integration` (from the latest `origin/master`) and do all the following steps within that branch.
* [ ] Add `.travis.yml` using `pre-commit` as a script. Set it up to run Python 3.8 env and add PIP caching. Ensure you install `pre-commit` before running tests. It should look like this:
```yaml
language: python
python: 3.8
cache: pip
before_install: pip install -U pre-commit
script: pre-commit run --all-files
```
* [ ] Push the branch and create a Pull Request for merging it into master.
